### ISSUE TITLE
For sound_board_0, load a background sound

### ISSUE THREAD

**Issue by pedrobeling** [oventi/tutoring-pedrobeling#2]
Create a on/off button to switch background music on and off within the sound board.

**Comment by pedrobeling** [comment]
Couldn't manage to do it in one button, created two buttons instead.

**Comment by oventi** [comment]
I wrote some comments here: https://github.com/oventi/tutoring-pedrobeling/commit/f69b4d47b47908dc3d04a39a7e80160f2f84c01d 

Also, you can use the `paused` property to have a single button https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/paused 

For example, 
```
if(music.paused) {
  play_background_music()
}
else {
  pause_background_music()
}
```

**Comment by oventi** [comment]
Based on our one on one session, this is solved.
