### ISSUE TITLE
Add a background image

### ISSUE THREAD

**Issue by oventi** [oventi/tutoring-pedrobeling#3]
Above the title in index.html, add this bit of code

```
<!-- add custom css between the style tag -->
<style type="text/css">

</style>
```

Then read this tutorial https://css-tricks.com/almanac/properties/b/background-image/ which will show you how to use the `background-image` property. 

Then find a good background image and add it to the index.html file. 

cheers.

**Comment by pedrobeling** [comment]
Done!

**Comment by oventi** [comment]
The background image is not appearing for me. I checked the code and I think you are not using the exact file name. Make sure the name of the file and what you put in the css matches exactly.

**Comment by oventi** [comment]
Also, when doing issues, commit your code one per issue, so you should have one commit for the bg image and one commit for the bg sound.

**Comment by oventi** [comment]
Thanks for the update, this works.
