### ISSUE TITLE
Loading background music file

### ISSUE THREAD

**Issue by pedrobeling** [oventi/tutoring-pedrobeling#6]
I tried to load the background music file but could only do so if I deleted the background event handler on the sound_board.js file.

And by doing that I also lose the play/pause functionality.

Is there a way to declare the const background_music on the background event music handler?

**Comment by oventi** [comment]
there is a way to load the background music from the json, not necessarily declaring the background music variable in a different place.

However, for now I want you to focus on the buttons, and when that is done we can move to this. keep the issue open though, to have a reference.

cheers.

**Comment by pedrobeling** [comment]
The issue #5 is solved. All button names and sound files loading as expected.

I shall wait for your feedback.

Cheers
________________________________

**Comment by oventi** [comment]
This issue has been solved.
